### ISSUE TITLE
add new circuit request

### ISSUE THREAD

**Issue by n8fr8** [guardianproject/orbot-ios#11]

**Comment by tladesignz** [comment]
In Tor Browser and Onion Browser, it can be requested, that only a specific circuit will be closed (and a new one built as replacement or a currently unused repurposed).

However, in Orbot, this is not possible, since there's no clean way for the user to select one and kill just that. Or better said: The user has no idea, which circuit is used for what domain, so it wouldn't help the user, even if they could select one.

Therefore, all circuits will be closed on the press of a button.

I put that button in the top. It starts getting crowded up there. Waiting for that redesign finish.
