### ISSUE TITLE
add circuit display

### ISSUE THREAD

**Issue by n8fr8** [guardianproject/orbot-ios#14]
from onion browser

**Comment by tladesignz** [comment]
It already has a rudimentary display: There's another tab labeled "Circuits" on the log fly-out. It shows all currently built non-internal circuits in a plain text list.

Onion Browser only shows the circuit, which it guesses is the one used for the current website. (It's definitely correct, when it's a circuit to an onion service and an educated guess, when it's not.)

Orbot doesn't have that context information. How do you suggest to improve the display of the existing circuits?

**Comment by tladesignz** [comment]
Oh, of course we could hand in the searched website via scheme handler/associated domain URL handling. 

Let's talk on the call on how to marry the current "show-all-viable-circuits" view with a "show circuits for a given domain" view and how to style both.

**Comment by tladesignz** [comment]
Since Orbot doesn't know about any called URLs, it can only show the full list of *all* circuits.

Instead of implementing a circuit scene displaying the circuit which most probably was used for a specific URL, Orbot 1.3.0 now implements a REST API (secured with authentication), where other apps can request this data and show it to their users.

So I consider this issue done.

If it turns out, we still need this to be in Orbot, we could reopen and use app URL query parameters to hand over the searched domain, but for now, I'll close this issue.
