### ISSUE TITLE
Pre-compiled binary releases

### ISSUE THREAD

**Issue by BionicBison05** [guardianproject/orbot-ios#3]
It would be useful to have ipa files for each release just as the Android repo has apk files, for the purpose of both sideloading and beta testing. For sideloading in particular, there are Windows methods for doing so while there is practically no way to build from source without a Mac.

**Comment by n8fr8** [comment]
Agreed. @tladesignz any thoughts on why not to post IPA files of releases?

**Comment by tladesignz** [comment]
Ok, this is the situation:

- I can do a normal build but instead of automatically uploading it to App Store Connect, I can have an IPA file created. However, that file cannot be installed. It is not correctly signed, yet, as the App Store has to put its signature on it, too.

- There is the possibility of "Ad Hoc" distribution. With that, I can create a distribution IPA, but **that is bound to certain devices**. We can add up to 100 device identifiers on a list [which can be found here](https://developer.apple.com/account/resources/devices/list), and these devices then can install the app. ((Actually less, because there's already dev devices in that list and we would need some buffer.) Getting these device identifiers from users is already difficult, and every time we need to add one, we would need to recreate the profile and do another build. Not a scalable solution. In fact, this was the original way of beta-testing before they bought up the TestFlight folks. Additionally, if the list is full, we need to wait 1 year until we can reset it.

- In theory, there's the Enterprise program, which would allow us to install apps on our "company devices". In practice, there's a tough screening process, we would never pass: https://developer.apple.com/programs/enterprise/

- We can do the same thing as the "Ad Hoc" distribution with a development build. The difference is just build flags.

- I can download the **"bought"** app [with the help of Apple Configurator 2](https://medium.com/testableapple/how-to-download-ipa-from-app-store-43e04b3d0332) from a device, but when I try to install it on a device without the account which "bought" it, iOS tells me to sign in with that account.

- The best thing we can actually do is to circulate a public TestFlight beta link. Limitations are: expiration after 90 days and 10k users max: https://help.apple.com/app-store-connect/#/devdc42b26b8 - and we might get a reaction from Apple, if that gets out of hand. (Like having 10k "beta" testers on constantly renewed "tests". We could get a slap on our wrists or completely deplatformed.

- I don't have a jailbroken device, so I can't test, if the IPA prepared for the store can be run there. I uploaded it here for others to test this: https://github.com/guardianproject/orbot-ios/releases/tag/v1.1.0

**Comment by tladesignz** [comment]
@BionicBison05, do you have a jailbroken device and can test the IPA I mentioned above?

**Comment by BionicBison05** [comment]
I have the AltStore, which automates the process of self-signing an IPA with the help of a PC. Like a more complicated way of allowing direct APK installation on Android. I can test the IPA.

**Comment by tladesignz** [comment]
Interesting: https://altstore.io
Someone got **really** pissed at Apple and did a *huge* workaround. Unfortunately, no commit since 2 years. Doesn't work on latest MacOS Monterey, because the plugin for Mail to intercept the mail traffic to enable code signing doesn't work anymore.

**Comment by BionicBison05** [comment]
Interesting. I've been using just fine on Monterey, in fact when I upgraded from Big Sur the AltStore server app prompted me to upgrade for Monterey compatibility. I will install the IPA when I'm at my computer later today and let you know how it works out.

**Comment by BionicBison05** [comment]
I've installed it through AltStore successfully but it's stuck at this screen with the install button nonfunctional. Any troubleshooting tips or does this mean that sideloading isn't an option? TestFlight may be the best option in that case. ![image](https://user-images.githubusercontent.com/93722725/156419478-9bdf717e-6ecb-4dbe-bdae-ecbdeee22130.png)

**Comment by BionicBison05** [comment]
Not jailbroken at all, but seems like signing with a free developer account breaks the network extension (which I have experienced when sideloading before.) TestFlight appears to be the most accessible option outside of requiring a jailbroken device for beta testing.

**Comment by tladesignz** [comment]
Ah, ok. So I thought you'd use a jailbroken device. Ok, then probably the AltStore just doesn't properly handle signing app extensions. It's a really cool tool. What a pity, that it's gotten orphaned.

Well, thanks anyway, for your support!
